name: Chore
description: Maintenance tasks and housekeeping
labels: []
type: chore
body:
  - type: textarea
    id: chore-description
    attributes:
      label: Chore Description
      description: What needs to be done?
      placeholder: Describe the maintenance task...
    validations:
      required: false