name: Enhancement
description: Improve an existing feature
labels: []
type: enhancement
body: 
  - type: textarea
    id: proposed-enhancement
    attributes:
      label: Proposed Enhancement
      description: How should it be improved?
      placeholder: Describe the enhancement in detail...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What value does this enhancement provide?
      placeholder: Explain the benefits to users, performance, maintainability, etc...
    validations:
      required: false
