name: Feature
description: Request a new feature using a structured form
title: ""
labels: []
type: feature
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Description of new feature
      placeholder: Describe the feature...
    validations:
      required: true