name: Requirement
description: Document a requirement specification
title: "[REQ] "
labels: []
type: requirement
body:
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Requirement justification; why is this requiremented valuable or necessary?
      placeholder: Explain why this requirement is needed...
    validations:
      required: true

  - type: textarea
    id: verification-criteria
    attributes:
      label: Verification Criteria
      description: List of criteria necessary for this requirement to be considered fulfilled
      placeholder: |
        - Criterion 1
        - Criterion 2
        - Criterion 3
    validations:
      required: false