blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Chicken-Chainsaws/project-management
    about: Check the project documentation for additional information